$fetch_if_allowed_output = "{ id: Integer, studio_person_id: Integer, email: String, parent_email: String, encrypted_password: String, reset_password_token: String, reset_password_sent_at: Time or DateTime, remember_created_at: Time or DateTime, sign_in_count: Integer, current_sign_in_at: Time or DateTime, last_sign_in_at: Time or DateTime, current_sign_in_ip: String, last_sign_in_ip: String, created_at: Time or DateTime, updated_at: Time or DateTime, username: String, provider: String, uid: String, admin: false or true, gender: String, name: String, locale: String, birthday: Date, user_type: String, school: String, full_address: String, school_info_id: Integer, total_lines: Integer, secret_picture_id: Integer, active: false or true, hashed_email: String, deleted_at: Time or DateTime, purged_at: Time or DateTime, secret_words: String, properties: String, invitation_token: String, invitation_created_at: Time or DateTime, invitation_sent_at: Time or DateTime, invitation_accepted_at: Time or DateTime, invitation_limit: Integer, invited_by_id: Integer, invited_by_type: String, invitations_count: Integer, terms_of_service_version: Integer, urm: false or true, races: String, primary_contact_info_id: Integer, path: String, age: String or Integer }"

$user_record = "{ id: Integer, studio_person_id: Integer, email: String, parent_email: String, encrypted_password: String, reset_password_token: String, reset_password_sent_at: Time or DateTime, remember_created_at: Time or DateTime, sign_in_count: Integer, current_sign_in_at: Time or DateTime, last_sign_in_at: Time or DateTime, current_sign_in_ip: String, last_sign_in_ip: String, created_at: Time or DateTime, updated_at: Time or DateTime, username: String, provider: String, uid: String, admin: false or true, gender: String, name: String, locale: String, birthday: Date, user_type: String, school: String, full_address: String, school_info_id: Integer, total_lines: Integer, secret_picture_id: Integer, active: false or true, hashed_email: String, deleted_at: Time or DateTime, purged_at: Time or DateTime, secret_words: String, properties: String, invitation_token: String, invitation_created_at: Time or DateTime, invitation_sent_at: Time or DateTime, invitation_accepted_at: Time or DateTime, invitation_limit: Integer, invited_by_id: Integer, invited_by_type: String, invitations_count: Integer, terms_of_service_version: Integer, urm: false or true, races: String, primary_contact_info_id: Integer } or { id: Integer, email: String, encrypted_password: String, reset_password_token: String, reset_password_sent_at: Time or DateTime, remember_created_at: Time or DateTime, sign_in_count: Integer, current_sign_in_at: Time or DateTime, last_sign_in_at: Time or DateTime, current_sign_in_ip: String, last_sign_in_ip: String, created_at: Time or DateTime, updated_at: Time or DateTime, username: String, provider: String, uid: String, admin: false or true, gender: String, name: String, language: String, birthday: Date, parent_email: String, deleted_at: DateTime or Time, hashed_email: String, properties: String, user_type: String, school: String, full_address: String, address: String, city: String, state: String, zip: String, lat: Float, lon: Float, total_lines: Integer, secret_words: String, secret_picture_id: Integer, secret_word_1_id: Integer, secret_word_2_id: Integer }"

$section_record = "{ id: Integer, user_id: Integer, name: String, created_at: Time or DateTime, updated_at: Time or DateTime, code: String, deleted_at: Time or DateTime, login_type: String, script_id: Integer, login_method: Integer, grade: String, admin_code: String, stage_extras: false or true, pairing_allowed: false or true, hidden: false or true, course_id: Integer, sharing_disabled: false or true, student_user_id: Integer, section_id: Integer, email: String, encrypted_password: String, reset_password_token: String, reset_password_sent_at: Time or DateTime, remember_created_at: Time or DateTime, sign_in_count: Integer, current_sign_in_at: Time or DateTime, last_sign_in_at: Time or DateTime, current_sign_in_ip: String, last_sign_in_ip: String, username: String, provider: String, uid: String, admin: false or true, gender: String, language: String, birthday: Date, parent_email: String, hashed_email: String, properties: String, user_type: String, school: String, full_address: String, address: String, city: String, state: String, zip: String, lat: Float, lon: Float, total_lines: Integer, secret_words: String, secret_picture_id: Integer, secret_word_1_id: Integer, secret_word_2_id: Integer }"

$student_record = "{ name: String, age: Integer, gender: String, birthday: Date, sharing_disabled: %bool, id: Integer, admin: %bool }"

$script_record = "{ id: Integer, name: String, created_at: DateTime or Time, updated_at: DateTime or Time, wrapup_video_id: Integer, hidden: false or true, user_id: Integer, login_required: false or true, properties: String, new_name: String, family_name: String }"

$storage_apps_record = "{ id: Integer, storage_id: Integer, value: String, updated_at: Time or DateTime, updated_ip: String, state: String, created_at: Time or DateTime, abuse_score: Integer, project_type: String, published_at: Time or DateTime, standalone: false or true, remix_parent_id: Integer }"

