$user_record = "{ id: Integer, email: String, encrypted_password: String, reset_password_token: String, reset_password_sent_at: DateTime or Time, remember_created_at: DateTime or Time, sign_in_count: Integer, current_sign_in_at: DateTime or Time, last_sign_in_at: DateTime or Time, current_sign_in_ip: String, last_sign_in_ip: String, created_at: DateTime or Time, updated_at: DateTime or Time, username: String, provider: String, uid: String, admin: false or true, gender: String, name: String, language: String, birthday: Date, parent_email: String, deleted_at: DateTime or Time, hashed_email: String, properties: String, user_type: String, school: String, full_address: String, address: String, city: String, state: String, zip: String, lat: Float, lon: Float, total_lines: Integer, secret_words: String, secret_picture_id: Integer, secret_word_1_id: Integer, secret_word_2_id: Integer }"

$section_record = "{ id: Integer, user_id: Integer, name: String, created_at: Time or DateTime, updated_at: Time or DateTime, code: String, deleted_at: Time or DateTime, login_type: String, script_id: Integer, login_method: Integer, grade: String, admin_code: String, stage_extras: false or true, pairing_allowed: false or true, hidden: false or true, course_id: Integer, sharing_disabled: false or true, student_user_id: Integer, section_id: Integer, email: String, encrypted_password: String, reset_password_token: String, reset_password_sent_at: Time or DateTime, remember_created_at: Time or DateTime, sign_in_count: Integer, current_sign_in_at: Time or DateTime, last_sign_in_at: Time or DateTime, current_sign_in_ip: String, last_sign_in_ip: String, username: String, provider: String, uid: String, admin: false or true, gender: String, language: String, birthday: Date, parent_email: String, hashed_email: String, properties: String, user_type: String, school: String, full_address: String, address: String, city: String, state: String, zip: String, lat: Float, lon: Float, total_lines: Integer, secret_words: String, secret_picture_id: Integer, secret_word_1_id: Integer, secret_word_2_id: Integer }"

$fetch_if_allowed_output = "{ id: Integer, email: String, encrypted_password: String, reset_password_token: String, reset_password_sent_at: DateTime or Time, remember_created_at: DateTime or Time, sign_in_count: Integer, current_sign_in_at: DateTime or Time, last_sign_in_at: DateTime or Time, current_sign_in_ip: String, last_sign_in_ip: String, created_at: DateTime or Time, updated_at: DateTime or Time, username: String, provider: String, uid: String, admin: false or true, gender: String, name: String, language: String, birthday: Date, parent_email: String, deleted_at: DateTime or Time, hashed_email: String, properties: String, user_type: String, school: String, full_address: String, address: String, city: String, state: String, zip: String, lat: Float, lon: Float, total_lines: Integer, secret_words: String, secret_picture_id: Integer, secret_word_1_id: Integer, secret_word_2_id: Integer, path: String, age: String or Integer }"

$student_record = "{ name: String, age: Integer, gender: String, birthday: Date, sharing_disabled: %bool, id: Integer, admin: %bool }"

$script_record = "{ id: Integer, name: String, created_at: Time or DateTime, updated_at: Time or DateTime, wrapup_video_id: Integer, hidden: %bool, trophies: %bool }"

$storage_apps_record = "{ id: Integer, storage_id: Integer, value: String, updated_at: Time or DateTime, updated_ip: String, state: String, created_at: Time or DateTime, abuse_score: Integer, project_type: String, published_at: Time or DateTime, standalone: false or true, remix_parent_id: Integer }"
